### ISSUE TITLE
Kategorijų palaikymas

### ISSUE THREAD

**Issue by aidiss** [shyrshe/Python-so-so-green#1]
Tracks time of completing a specific task.
---
First need to establish task categories:
1. email
2. information
3. meeting
4. paper_work
5. consultation

Each task has an assigned code (number) for simpler control (maybe dictionary?).

Program asks to input a task code (e.g. '1') and automatically saves task completion time files under full task name (e.g. 'email.txt') 
when input is not a preassigned code, will ask whether input is correct, 
if yes, creates a file under the new - inputted - task name
else - will ask for code again

**Comment by shyrshe** [comment]
**First**. 
Create a dict with codes assigned to categories. 
Ability to input a category.
